mychichair/dashboard/order/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.OrderListView.as_view(), name='orders'),
    url(r'^(?P<order_pk>\d+)/$',
        views.order_details, name='order-details'),
    url(r'^(?P<order_pk>\d+)/add-note/$',
        views.order_add_note, name='order-add-note'),
    url(r'^(?P<order_pk>\d+)/cancel/$',
        views.cancel_order, name='order-cancel'),
    url(r'^(?P<order_pk>\d+)/address/(?P<address_type>billing|shipping)/$',
        views.address_view, name='address-edit'),

    url(r'^(?P<order_pk>\d+)/payment/(?P<payment_pk>\d+)/capture/$',
        views.capture_payment, name='capture-payment'),
    url(r'^(?P<order_pk>\d+)/payment/(?P<payment_pk>\d+)/release/$',
        views.release_payment, name='release-payment'),
    url(r'^(?P<order_pk>\d+)/payment/(?P<payment_pk>\d+)/refund/$',
        views.refund_payment, name='refund-payment'),

    url(r'^(?P<order_pk>\d+)/line/(?P<line_pk>\d+)/change/$',
        views.orderline_change_quantity, name='orderline-change-quantity'),
    url(r'^(?P<order_pk>\d+)/line/(?P<line_pk>\d+)/split/$',
        views.orderline_split, name='orderline-split'),
    url(r'^(?P<order_pk>\d+)/line/(?P<line_pk>\d+)/cancel/$',
        views.orderline_cancel, name='orderline-cancel'),
    url(r'^(?P<order_pk>\d+)/remove-voucher/$',
        views.remove_order_voucher, name='order-remove-voucher'),
    url(r'^(?P<order_pk>\d+)/shipment/(?P<group_pk>\d+)/ship/$',
        views.ship_delivery_group, name='ship-delivery-group'),
    url(r'^(?P<order_pk>\d+)/shipment/(?P<group_pk>\d+)/cancel/$',
        views.cancel_delivery_group, name='cancel-delivery-group')]

mychichair/dashboard/payments/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.PaymentList.as_view(), name='payments'),
    url(r'^(?P<pk>[0-9]+)/$', views.payment_details, name='payment-details')
]

mychichair/order/urls.py
from django.conf.urls import url

from ..core import TOKEN_PATTERN
from . import views


urlpatterns = [
    url(r'^%s/$' % (TOKEN_PATTERN,), views.details, name='details'),
    url(r'^%s/payment/$' % (TOKEN_PATTERN,),
        views.payment, name='payment'),
    url(r'^%s/payment/(?P<variant>[-\w]+)/$' % (TOKEN_PATTERN,),
        views.start_payment, name='payment'),
    url(r'^%s/cancel-payment/$' % (TOKEN_PATTERN,), views.cancel_payment,
        name='cancel-payment')
]

mychichair/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.views import serve

from .cart.urls import urlpatterns as cart_urls
from .messages.urls import urlpatterns as messages_urls
from .checkout.urls import urlpatterns as checkout_urls
from .core.sitemaps import sitemaps
from .core.urls import urlpatterns as core_urls
from .order.urls import urlpatterns as order_urls
from .product.urls import urlpatterns as product_urls
from .registration.urls import urlpatterns as registration_urls
from .userprofile.urls import urlpatterns as userprofile_urls
from .dashboard.urls import urlpatterns as dashboard_urls


admin.autodiscover()

urlpatterns = [
    url(r'^', include(core_urls)),
    url(r'^api/messages', include(messages_urls, namespace='messages')),
    url(r'^account/', include(registration_urls, namespace='registration')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^cart/', include(cart_urls, namespace='cart')),
    url(r'^checkout/', include(checkout_urls, namespace='checkout')),
    url(r'^dashboard/', include(dashboard_urls, namespace='dashboard')),
    url(r'^order/', include(order_urls, namespace='order')),
    url(r'^products/', include(product_urls, namespace='product')),
    url(r'^profile/', include(userprofile_urls, namespace='profile')),
    url(r'^selectable/', include('selectable.urls')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'', include('payments.urls')),
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', serve)
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mychichair/cart/models.py
from __future__ import unicode_literals
from . import logger

from collections import namedtuple
from uuid import uuid4

from decimal import Decimal
from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.utils.encoding import python_2_unicode_compatible, smart_str
from django.utils.timezone import now
from django.utils.translation import pgettext_lazy
from django_prices.models import PriceField
from jsonfield import JSONField
from satchless.item import ItemLine, ItemSet, ItemList, partition

from ..discount.models import Voucher
from ..product.models import ProductVariant

CENTS = Decimal('0.01')


SimpleCart = namedtuple('SimpleCart', ('quantity', 'total', 'token'))


class ProductGroup(ItemList):
    def is_shipping_required(self):
        return any(p.is_shipping_required() for p in self)


class CartQueryset(models.QuerySet):

    def anonymous(self):
        return self.filter(user=None)

    def open(self):
        return self.filter(status=Cart.OPEN)

    def saved(self):
        return self.filter(status=Cart.SAVED)

    def waiting_for_payment(self):
        return self.filter(status=Cart.WAITING_FOR_PAYMENT)

    def checkout(self):
        return self.filter(status=Cart.CHECKOUT)

    def canceled(self):
        return self.filter(status=Cart.CANCELED)

    def save(self):
        self.update(status=Cart.SAVED)


class Cart(models.Model, ItemSet):

    COOKIE_NAME = 'cart'

    OPEN, SAVED, WAITING_FOR_PAYMENT, ORDERED, CHECKOUT, CANCELED = (
        'open', 'saved', 'payment', 'ordered', 'checkout', 'canceled')

    STATUS_CHOICES = (
        (OPEN, pgettext_lazy('Cart', 'Open - currently active')),
        (WAITING_FOR_PAYMENT, pgettext_lazy('Cart', 'Waiting for payment')),
        (SAVED, pgettext_lazy(
            'Cart', 'Saved - for items to be purchased later')),
        (ORDERED, pgettext_lazy(
            'Cart', 'Submitted - has been ordered at the checkout')),
        (CHECKOUT, pgettext_lazy(
            'Cart', 'Checkout - basket is processed in checkout')),
        (CANCELED, pgettext_lazy(
            'Cart', 'Canceled - basket was canceled by user'))
    )

    status = models.CharField(
        pgettext_lazy('Cart', 'order status'),
        max_length=32, choices=STATUS_CHOICES, default=OPEN)
    created = models.DateTimeField(
        pgettext_lazy('Cart', 'created'), auto_now_add=True)
    last_status_change = models.DateTimeField(
        pgettext_lazy('Cart', 'last status change'), auto_now_add=True)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, blank=True, null=True, related_name='carts',
        verbose_name=pgettext_lazy('Cart', 'user'))
    email = models.EmailField(blank=True, null=True)
    token = models.UUIDField(pgettext_lazy('Cart', 'token'),
                             primary_key=True, default=uuid4, editable=False)
    voucher = models.ForeignKey(
        Voucher, null=True, related_name='+', on_delete=models.SET_NULL)
    checkout_data = JSONField(null=True, editable=False)

    total = PriceField(
        currency=settings.DEFAULT_CURRENCY, max_digits=12, decimal_places=2,
        default=0)
    quantity = models.PositiveIntegerField(default=0)

    objects = CartQueryset.as_manager()

    class Meta:
        ordering = ('-last_status_change',)

    def __init__(self, *args, **kwargs):
        self.discounts = kwargs.pop('discounts', None)
        super(Cart, self).__init__(*args, **kwargs)

    def update_quantity(self):
        total_lines = self.count()['total_quantity']
        if not total_lines:
            total_lines = 0
        self.quantity = total_lines
        self.save(update_fields=['quantity'])

    def change_status(self, status):
        if status not in dict(self.STATUS_CHOICES):
            raise ValueError('Not expected status')
        if status != self.status:
            self.status = status
            self.last_status_change = now()
            self.save()

    def change_user(self, user):
        open_cart = Cart.get_user_open_cart(user)
        if open_cart is not None:
            open_cart.change_status(status=Cart.CANCELED)
        self.user = user
        self.save(update_fields=['user'])

    @staticmethod
    def get_user_open_cart(user):
        carts = user.carts.open()
        if len(carts) > 1:
            logger.warning('%s has more than one open basket', user)
            for cart in carts[1:]:
                cart.change_status(Cart.CANCELED)
        return carts.first()

    def is_shipping_required(self):
        return any(line.is_shipping_required() for line in self.lines.all())

    #Satchless
    def __repr__(self):
        return 'Cart(quantity=%s)' % (self.quantity,)

    def __iter__(self):
        return iter(self.lines.all())

    def __len__(self):
        return self.lines.count()

    def count(self):
        lines = self.lines.all()
        return lines.aggregate(total_quantity=models.Sum('quantity'))

    def clear(self):
        self.delete()

    def create_line(self, variant, quantity, data):
        line = self.lines.create(variant=variant, quantity=quantity, data=data)
        return line

    def get_line(self, variant, data=None):
        try:
            return self.lines.get(variant=variant)
        except CartLine.DoesNotExist:
            return None

    def add(self, variant, quantity=1, data=None, replace=False,
            check_quantity=True):
        cart_line, created = self.lines.get_or_create(
            variant=variant, defaults={'quantity': 0, 'data': data})
        if replace:
            new_quantity = quantity
        else:
            new_quantity = cart_line.quantity + quantity

        if new_quantity < 0:
            raise ValueError('%r is not a valid quantity (results in %r)' % (
                quantity, new_quantity))

        if check_quantity:
            variant.check_quantity(new_quantity)

        cart_line.quantity = new_quantity

        if not cart_line.quantity:
            cart_line.delete()
        else:
            cart_line.save(update_fields=['quantity'])
        self.update_quantity()

    def partition(self):
        grouper = (
            lambda p: 'physical' if p.is_shipping_required() else 'digital')
        return partition(self, grouper, ProductGroup)


@python_2_unicode_compatible
class CartLine(models.Model, ItemLine):

    cart = models.ForeignKey(Cart, related_name='lines')
    variant = models.ForeignKey(
        ProductVariant, related_name='+',
        verbose_name=pgettext_lazy('Cart line', 'product'))
    quantity = models.PositiveIntegerField(
        pgettext_lazy('Cart line', 'quantity'),
        validators=[MinValueValidator(0), MaxValueValidator(999)])
    data = JSONField(blank=True, default={})


    class Meta:
        unique_together = ('cart', 'variant', 'data')

    def __str__(self):
        return smart_str(self.variant)

    # Satchless
    def __eq__(self, other):
        if not isinstance(other, CartLine):
            return NotImplemented

        return (self.variant == other.variant and
                self.quantity == other.quantity and
                self.data == other.data)

    def __ne__(self, other):
        return not self == other  # pragma: no cover

    def __repr__(self):
        return 'CartLine(variant=%r, quantity=%r, data=%r)' % (
            self.variant, self.quantity, self.data)

    def __getstate__(self):
        return self.variant, self.quantity, self.data

    def __setstate__(self, data):
        self.variant, self.quantity, self.data = data

    def get_total(self, **kwargs):
        amount = super(CartLine, self).get_total(**kwargs)
        return amount.quantize(CENTS)

    def get_quantity(self, **kwargs):
        return self.quantity

    def get_price_per_item(self, discounts=None, **kwargs):
        return self.variant.get_price_per_item(discounts=discounts, **kwargs)

    def is_shipping_required(self):
        return self.variant.is_shipping_required()

mychichair/order/forms.py
from django import forms
from django.conf import settings
from django.utils.translation import ugettext_lazy as _

from .models import Payment


class PaymentMethodsForm(forms.Form):
    method = forms.ChoiceField(
        choices=settings.CHECKOUT_PAYMENT_CHOICES, widget=forms.RadioSelect,
        initial=settings.CHECKOUT_PAYMENT_CHOICES[0][0], label=_('Méthode'))


class PaymentDeleteForm(forms.Form):
    payment_id = forms.IntegerField(widget=forms.HiddenInput())

    def __init__(self, *args, **kwargs):
        self.order = kwargs.pop('order')
        super(PaymentDeleteForm, self).__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super(PaymentDeleteForm, self).clean()
        payment_id = cleaned_data.get('payment_id')
        waiting_payments = self.order.payments.filter(status='waiting')
        try:
            payment = waiting_payments.get(id=payment_id)
        except Payment.DoesNotExist:
            self._errors['number'] = self.error_class(
                [_('Payment does not exist')])
        else:
            cleaned_data['payment'] = payment
        return cleaned_data

    def save(self):
        payment = self.cleaned_data['payment']
        payment.status = 'rejected'
        payment.save()

mychichair/dashboard/payments/views.py
from django.shortcuts import get_object_or_404
from django.template.response import TemplateResponse
from django.views.generic import ListView
from payments.models import PAYMENT_STATUS_CHOICES

from ..views import (FilterByStatusMixin, StaffMemberOnlyMixin,
                     staff_member_required)
from ...order.models import Payment
from ..order.forms import PaymentFilterForm


class PaymentList(StaffMemberOnlyMixin, FilterByStatusMixin, ListView):
    model = Payment
    template_name = 'dashboard/payments/list.html'
    context_object_name = 'payments'
    paginate_by = 30
    form_class = PaymentFilterForm
    status_choices = PAYMENT_STATUS_CHOICES
    status_order = ['waiting', 'input', 'preauth', 'confirmed', 'refunded',
                    'rejected', 'error']

    def get_queryset(self):
        qs = super(PaymentList, self).get_queryset()
        return qs.order_by('-created').select_related('order')


@staff_member_required
def payment_details(request, pk):
    payment = get_object_or_404(Payment, pk=pk)
    return TemplateResponse(request, 'dashboard/payments/detail.html',
                            {'payment': payment})

templates/order/details.html
{% extends "base.html" %}

{% load gross from prices_i18n %}
{% load i18n %}
{% load staticfiles %}
{% load discount_amount_for from prices %}

{% block title %}{% trans "Order" %} {{ order }} — {{ block.super }}{% endblock %}

{% block breadcrumb %}
    {% if order.user == user %}
        <li class="m_right_10 current">
            <a href="/" class="default_t_color">
                {% trans "Accueil" %}
                <i class="fa fa-angle-right d_inline_middle m_left_10"></i>
            </a>
        </li>
        <li class="m_right_10 current">
            <a href="{% url 'profile:orders' %}" class="default_t_color">
                {% trans "Vos commandes" %}
                <i class="fa fa-angle-right d_inline_middle m_left_10"></i>
            </a>
        </li>
        <li><a href=href="{% url 'order:details' token=order.token %}" class="default_t_color">{{ order }}</a></li>
    {% endif %}
{% endblock breadcrumb %}

{% block content %}
    {# This view is available by just knowing url,          #}
    {# so we don't show all details (like delivery address) #}
    {# unless current user is owner of the order.           #}

    <div class="row">
        <div class="col-sm-12">
            <h3 class="page-header page-header--order">
                <span class="text-muted">{% blocktrans %}Order {{ order }}: {% endblocktrans %}</span>
                {{ order.get_status_display }}

                {% if not order.is_fully_paid %}
                    {% if order.is_pre_authorized %}
                        <a href="{% url "order:payment" token=order.token %}"
                           class="btn button_type_6 bg_scheme_color f_size_large r_corners tr_all_hover color_light m_bottom_20">{% trans "D&eacute;tails de paiement" %}</a>
                    {% else %}
                        <a href="{% url "order:payment" token=order.token %}"
                           class="btn button_type_6 bg_scheme_color f_size_large r_corners tr_all_hover color_light m_bottom_20">{% trans "Payer la commande" %}</a>
                    {% endif %}
                {% endif %}
            </h3>
        </div>
    </div>

    <div class="row">
        {% if order.user == user %}
            <div class="col-sm-6">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        {% trans "Adresse de facturation" %}
                    </div>
                    <div class="panel-body">
                        <address>{% include "userprofile/snippets/address-details.html" with address=order.billing_address %}</address>
                    </div>
                </div>
            </div>
            {% if order.is_shipping_required %}
                <div class="col-sm-6">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            {% trans "Adresse de livraison" %}
                        </div>
                        <div class="panel-body">
                            <address>{% include "userprofile/snippets/address-details.html" with address=order.shipping_address %}</address>
                        </div>
                    </div>
                </div>
            {% endif %}
        {% endif %}
    </div>

    {% for group in groups %}
        <div class="panel panel-default">
            <div class="panel-heading">
                {% blocktrans with number=forloop.counter %}Envoi #{{ number }}{% endblocktrans %}
                <span class="pull-right">
                    <span class="label label-default">{{ group.get_status_display }}</span>
                </span>
            </div>
            <table class="table">
                <thead>
                <tr>
                    <th class="col-sm-6">{% trans "Nom" %}</th>
                    <th class="col-sm-3 text-right">{% trans "Prix" %}</th>
                    <th class="col-sm-3 text-right">{% trans "Sous-total" %}</th>
                </tr>
                </thead>
                <tfoot>
                <tr>
                    <th colspan="2">{% trans "Total" %}</th>
                    <th class="text-right">{% gross group.get_total %}</th>
                </tr>
                </tfoot>
                <tbody>
                {% for item in group %}
                    <tr>
                        <td>{{ item.product }}{% if item.quantity != 1 %} <em>×{{ item.quantity }}</em>{% endif %}</td>
                        <td class="text-right">{% gross item.get_price_per_item %}</td>
                        <td class="text-right">{% gross item.get_total %}</td>
                    </tr>
                {% endfor %}
                {% if group.shipping_price.gross %}
                    <tr>
                        <td class="col-sm-4">
                            {% trans "Livraison" %}
                        </td>
                        <td class="text-right">{% gross group.shipping_price %}</td>
                        <td class="text-right">{% gross group.shipping_price %}</td>
                    </tr>
                {% endif %}
                </tbody>
            </table>
        </div>
    {% endfor %}
    {% if order.discount_amount %}
        <div class="panel panel-default">
            <div class="panel-heading">
                {{ order.discount_name }}
            </div>
            <div class="panel-body text-right">
                <strong>{% gross order.discount|discount_amount_for:order.total %}</strong>
            </div>
        </div>
    {% endif %}
    {% if order.discount_amount or groups|length > 1 %}
        <div class="panel panel-default">
            <div class="panel-heading">
                {% trans "Total" %}
            </div>
            <div class="panel-body text-right">
                <strong>{% gross order.total %}</strong>
            </div>
        </div>
    {% endif %}
{% endblock content %}

templates/order/payment.html
{% extends "base.html" %}

{% load bootstrap_form from bootstrap3 %}
{% load gross from prices_i18n %}
{% load discount_amount_for from prices %}
{% load i18n %}
{% load staticfiles %}

{% block title %}{% trans "Paiement de la commande" %} {{ order }} — {{ block.super }}{% endblock %}

{% block breadcrumb %}
    {% if order.user == user %}
        <li class="m_right_10 current">
            <a href="/" class="default_t_color">
                {% trans "Accueil" %}
                <i class="fa fa-angle-right d_inline_middle m_left_10"></i>
            </a>
        </li>
        <li class="m_right_10 current">
            <a href="{% url 'profile:orders' %}" class="default_t_color">
                {% trans "Vos commandes" %}
                <i class="fa fa-angle-right d_inline_middle m_left_10"></i>
            </a>
        </li>
        <li><a href=href="{% url 'order:details' token=order.token %}" class="default_t_color">{{ order }}</a></li>
    {% endif %}
{% endblock breadcrumb %}

{% block content %}
    <div class="row">
        <div class="col-sm-8">
            {% if order.user == user or not order.is_fully_paid %}
                {% if not order.is_fully_paid %}
                    <div class="panel panel-info color-scheme">
                        {% if waiting_payment %}
                            <div class="panel-heading">
                                {% trans "Paiement en attente" %}
                            </div>
                            <div class="panel-body">
                                <form method="post" action="{% url 'order:cancel-payment' token=order.token %}">
                                    {% csrf_token %}
                                    <p>{% trans "Nous attendons une autorisation pour votre paiement." %}</p>
                                    <p>{% trans "Statut actuel" %}: <span
                                            class="label label-default">{{ waiting_payment.get_status_display }}</span>
                                    </p>
                                    <p>{% trans "A moins d&rsquo;&ecirc;tre s&ucirc;r que le paiement ait &eacute;chou&eacute;, attendez avant d'en refaire un pour &eacute;viter d'&ecirc;tre d&eacute;bit&eacute; 2 fois." %}</p>
                                    {% bootstrap_form waiting_payment_form %}
                                    <button type="submit"
                                            class="btn btn-danger">{% trans "Je comprends, je veux tenter un nouveau paiement." %}</button>
                                </form>
                            </div>
                        {% elif payment_form %}
                            <div class="panel-heading">
                                {% trans "Paiement de la commande" %} {{ order }}
                            </div>
                            <div class="panel-body">
                                <form method="post" action="{% url "order:payment" token=order.token %}">
                                    {% csrf_token %}
                                    {{ payment_form }}
                                    <div class="form-group text-right">
                                        {% block form_submit %}
                                            <button type="submit" class="btn btn-primary color-scheme">
                                                {% trans "Confirmer la commande" %}
                                            </button>
                                        {% endblock %}
                                    </div>
                                </form>
                            </div>
                        {% else %}
                            <div class="panel-body alert-info color-scheme">
                                <span>{% trans "Votre transaction a &eacute;t&eacute; accept&eacute;e. Votre commande est en cours de traitement." %}</span>
                            </div>
                        {% endif %}
                    </div>
                {% endif %}
            {% endif %}
        </div>
    </div>

    <div class="row">
        {% if order.user == user %}
            <div class="col-sm-6">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        {% trans "Adresse de facturation" %}
                    </div>
                    <div class="panel-body">
                        <address>{% include "userprofile/snippets/address-details.html" with address=order.billing_address %}</address>
                    </div>
                </div>
            </div>

            <div class="col-sm-6">
                {% if order.is_shipping_required %}
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            {% trans "Adresse de livraison" %}
                        </div>
                        <div class="panel-body">
                            <address>{% include "userprofile/snippets/address-details.html" with address=order.shipping_address %}</address>
                        </div>
                    </div>
                {% endif %}
            </div>
        {% endif %}
    </div>

    {% for group in groups %}
        <div class="panel panel-default">
            <div class="panel-heading">
                {% blocktrans with number=forloop.counter %}Livraison #{{ number }}{% endblocktrans %}
            </div>
            <table class="table">
                <thead>
                <tr>
                    <th class="col-sm-6">{% trans "Nom" %}</th>
                    <th class="col-sm-3 text-right">{% trans "Prix" %}</th>
                    <th class="col-sm-3 text-right">{% trans "Sous-total" %}</th>
                </tr>
                </thead>
                <tfoot>
                <tr>
                    <th colspan="2">{% trans "Total" %}</th>
                    <th class="text-right">{% gross group.get_total %}</th>
                </tr>
                </tfoot>
                <tbody>
                {% for item in group %}
                    <tr>
                        <td>{{ item.product }}{% if item.quantity != 1 %} <em>×{{ item.quantity }}</em>{% endif %}</td>
                        <td class="text-right">{% gross item.get_price_per_item %}</td>
                        <td class="text-right">{% gross item.get_total %}</td>
                    </tr>
                {% endfor %}
                {% if group.shipping_price.gross %}
                    <tr>
                        <td class="col-sm-4">
                            {% trans "Livraison" %}
                        </td>
                        <td class="text-right">{% gross group.shipping_price %}</td>
                        <td class="text-right">{% gross group.shipping_price %}</td>
                    </tr>
                {% endif %}
                </tbody>
            </table>
        </div>
    {% endfor %}
    {% if order.discount_amount %}
        <div class="panel panel-default">
            <div class="panel-heading">
                {{ order.discount_name }}
            </div>
            <div class="panel-body text-right">
                <strong>{% gross order.discount|discount_amount_for:order.total %}</strong>
            </div>
        </div>
    {% endif %}
    {% if order.discount_amount or groups|length > 1 %}
        <div class="panel panel-default">
            <div class="panel-heading">
                {% trans "Total" %}
            </div>
            <div class="panel-body text-right">
                <strong>{% gross order.total %}</strong>
            </div>
        </div>
    {% endif %}
{% endblock content %}

templates/order/success.html
{% extends "base.html" %}
{% load gross from prices_i18n %}
{% load i18n %}

{% block title %}{% trans "Commande finalis&eacute;e!" %} — {{ block.super }}{% endblock %}


{% block content %}
<h2>{% trans "Votre commande est finalis&eacute;e." %}</h2>
<p>{% trans "Merci pour votre achat !" %}</p>

<p>{% trans "Votre num&eacute;ro de commande" %}: <a href="{% url 'order:details' token=order.token %}">{{ order }}</a></p>
{% endblock content %}

{% block google-analytics-script %}
    {{ block.super }}
    __ga('require', 'ecommerce', 'ecommerce.js');
    __ga('set', 'currencyCode', '{{ DEFAULT_CURRENCY }}');
    __ga('ecommerce:addTransaction', {
      'id': '{{ order.id }}',
      'affiliation': 'Saleor',
      'revenue': '{{ order.get_total.gross }}',
      'shipping': '{{ order.get_delivery_total.gross }}',
      'tax': '{{ order.get_total.tax }}'
    });
    {% for item in order.get_items %}
     __ga('ecommerce:addItem', {
        'id': '{{ item.id }}',
        'name': '{{ item }}',
        'sku': '{{ item.sku }}',
        'category': '{{ item.product.category }}',
        'price': '{{ item.unit_price_gross }}',
        'quantity': '{{ item.quantity }}'
      });
    {% endfor %}
    __ga('ecommerce:send');
{% endblock google-analytics-script %}